import type {
  DatabaseCredentials,
  RedisCredentials,
  StorageCredentials,
} from "@hostrig/shared"

export interface SecretsInput {
  database: DatabaseCredentials
  redis: RedisCredentials
  storage: StorageCredentials
}

/** Characters that make a YAML scalar unsafe to emit unquoted. */
const YAML_UNSAFE_RE = /[-:#\n\r"'{}[\],&*?|>!%@`\t]/

/**
 * Generates connection secrets for a project as YAML.
 */
export class SecretsService {
  generateSecretsYaml(input: SecretsInput): string {
    const lines = [
      "# Generated by Hostrig — treat as secret",
      "database:",
      `  host: ${yamlQuote(input.database.host)}`,
      `  port: ${input.database.port}`,
      `  name: ${yamlQuote(input.database.database)}`,
      `  user: ${yamlQuote(input.database.user)}`,
      `  password: ${yamlQuote(input.database.password)}`,
      input.database.url ? `  url: ${yamlQuote(input.database.url)}` : null,
      "redis:",
      `  host: ${yamlQuote(input.redis.host)}`,
      `  port: ${input.redis.port}`,
      input.redis.password
        ? `  password: ${yamlQuote(input.redis.password)}`
        : null,
      input.redis.namespace
        ? `  namespace: ${yamlQuote(input.redis.namespace)}`
        : null,
      input.redis.url ? `  url: ${yamlQuote(input.redis.url)}` : null,
      "storage:",
      `  endpoint: ${yamlQuote(input.storage.endpoint)}`,
      `  bucket: ${yamlQuote(input.storage.bucket)}`,
      `  accessKeyId: ${yamlQuote(input.storage.accessKeyId)}`,
      `  secretAccessKey: ${yamlQuote(input.storage.secretAccessKey)}`,
      input.storage.region
        ? `  region: ${yamlQuote(input.storage.region)}`
        : null,
    ]

    return lines.filter((line) => line != null).join("\n") + "\n"
  }
}

/**
 * Quote a YAML scalar value, defaulting to double-quoted JSON form when the
 * value contains any character that YAML would interpret specially.
 */
function yamlQuote(value: string): string {
  if (needsYamlQuoting(value)) return JSON.stringify(value)
  return value
}

function needsYamlQuoting(value: string): boolean {
  if (value === "") return true
  if (YAML_UNSAFE_RE.test(value)) return true
  if (value.includes(" ")) return true
  if (/^\d/.test(value)) return true
  if (/^(true|false|null|yes|no|on|off|~)$/i.test(value)) return true
  return false
}
